# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-sitemap, jekyll-seo-tag, jekyll-feed]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Konstantin Mordan'
description:	       'iOS Developer'
author:                'Konstantin Mordan'
