# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-134442936-1'

menu:
#- {name: 'About', path: 'menu', url: 'about.html'}
#- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/kmordan'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/mrdn'}
- {icon: 'twitter', link: 'https://twitter.com/k_mrdn'}
- {icon: 'facebook', link: 'https://www.facebook.com/konstantinmordan'}
- {icon: 'instagram', link: 'https://www.instagram.com/k.mrdn'}
- {icon: 'envelope', link: 'mailto:konstantinmordan@gmail.com'}
